### PR TITLE
Implemented Tactician CommandBus wrapper

### PR DESCRIPTION
**Pull request by boekkooi-fresh**
# What this PR changes:
- This PR adds a tactician wrapper that mirrors the SimpleCommandBus implementation but allows for custom middleware per projects.
# When reviewing, please consider:
- If we should just use Tactician as the default CommandBus and not have our own implementation.

### CODE REVIEW

**Comment by italolelis** [comment]
The tactician library was already added....
I appreciate if you can write some tests to it

**Comment by boekkooi-fresh** [comment]
@italolelis Where was it already added because I missed it. Also is https://github.com/hellofresh/engine/blob/0efbf912548b021a5a9be9b5db8037ad84d8f7fe/tests/CommandBus/TacticianCommandBusTest.php not enough?

**Comment by italolelis** [comment]
Here https://github.com/hellofresh/engine/blob/master/src/CommandBus/TacticianCommandBus.php

**Comment by boekkooi-fresh** [comment]
Ok my bad I missed that should I merge that commandbus with this one?

**Comment by italolelis** [comment]
I believe the best would be to create a new PR only with the updated tests 😄

**Comment by boekkooi-fresh** [comment]
Ok

**Pull request closed without merging**
