### PR TITLE
Add middleware and pipeline for better processing

### PR DESCRIPTION
**Pull request by rphcrosbyhf**
# What this PR changes:
- Adds a middleware pipeline and middleware interface
- This allows us to write middleware (such as loggers) for different tasks (such as event dispatches) whilst keeping separation of concerns.
- Supports before and after middleware
# When reviewing, please consider:
- The tests feel a little incomplete, any suggestions on a few more would be good.

### CODE REVIEW

**Comment by boekkooi-fresh** [comment]
@rphcrosbyhf Can you please explain a little more where this would be usefull. Since for the commandbus we have support for [tactician](https://github.com/thephpleague/tactician) which is based on middleware and for HTTP we use sylix which has events So where would we use this?

**Comment by italolelis** [comment]
I don't think middlewares are part of this project... It has absolutely nothing to do with this. You already have a dispatcher interface for events, or you can even use the event bus for hooking up to domain events.

Why would we use middlewares here?

**Comment by rphcrosbyhf** [comment]
[Here](https://github.com/hellofresh/carriers-service/blob/master/src/Infrastructure/Dispatcher/RabbitMQDispatcher.php) in the carrier service, events that are dispatched to RabbitMQ are logged before and after. 

Seemed abstract enough that it could be useful in this repo.

**Comment by italolelis** [comment]
That implementation was very specific for the RabbitMQ, most of the times we don't even need to log before and after events (specially on a dispatcher). That was useful for our ELK platform to know about the events.

**Comment by rphcrosbyhf** [comment]
Feel free to close then 👍

**Pull request closed without merging**
